apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-go-sample-multi-component-example-enmg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-go-sample-multi-component-example-enmg
    app.kubernetes.io/part-of: multi-component-example-1
  name: devfile-go-sample-multi-component-example-enmg
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-go-sample-multi-component-example-enmg
status:
  loadBalancer: {}
